site_name: LuMa.js Docs
pages: 
  - Home: index.md
  - Numbers: 
    - 'Constants': NA/Constants.md
    - 'Numeric Functions': NA/Numeric Functions.md
    - 'Series & Patterns': NA/Series.md
    - 'Complex Numbers': NA/Complex Numbers.md
    - 'Statistics': NA/Statistics.md
    - 'Sequences & Series': NA/Sequences and Series.md
    - 'Patterns': NA/Patterns.md
    - 'Procedural Generation': NA/Procedural Generation.md
  - Linear Algebra: 
    - Vectors: 
      - Classes:
        - 'Vec2': LA/Vec2.md
        - 'Vec3': LA/Vec3.md
        - 'Vec4': LA/Vec4.md
      - Operations: 
        - 'Vector Operations': LA/vectorOperations.md
        - 'Vector Addition': LA/vectorAddition.md
        - 'Vector Subtraction': LA/vectorSubtraction.md
        - 'Scalar Multiplication': LA/vectorScalarMultiplication.md
        - 'Scalar Division': LA/vectorScalarDivision.md
        - 'Negation': LA/vectorNegation.md
        - 'Lerp': LA/vectorLerp.md
        - 'Nlerp': LA/vectorNlerp.md
        - 'Slerp': LA/vectorSlerp.md
        - 'Dot (Scalar Product)': LA/vectorDot.md
        - 'Cross (Vector Product)': LA/vectorCross.md
        - 'Wedge (Exterior Product)': LA/vectorWedge.md
        - 'Magnitude': LA/vectorMagnitude.md
        - 'Magnitude Squared': LA/vectorMagnitudeSquared.md
        - 'Normalization': LA/vectorNormalization.md
        - 'Angle': LA/vectorAngle.md
        - 'AngleDirected': LA/vectorAngleDirected.md
        - 'Projection': LA/vectorProjection.md
        - 'Rejection': LA/vectorRejection.md
        - 'Reflection': LA/vectorReflection.md
        - 'Refraction': LA/vectorRefraction.md
    - Matrices: 
      - 'Classes': LA/matrixClasses.md
      - 'Operations': LA/matrixOperations.md
    - Quaternions: 
      - 'Classes': LA/quaternionClasses.md
      - 'Operations': LA/quaternionOperations.md
  - Geometry: 
    - 'Geometric Objects': GEO/Geometric Objects.md
    - 'Intersection Testing': GEO/Intersection Testing.md
  - Functions: 
    - 'Expressions': FC/Expressions.md
    - 'Calculus': FC/Calculus.md
docs:
  docs/
    imgs/
      vectorAdditionVariables.png
# theme: readthedocs
markdown_extesions:
  - pymdownx.arithmatex
extra_javascript:
  # - mathjax-config.js # Used for equation numbering
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css: [extra.css]